name: Reusable workflow - Run dbt

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      full_refresh:
        required: false
        type: boolean
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true

jobs:
  dbt_run:
    name: dbt_run
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.10.x"

      - name: Load .env file
        uses: xom9ikk/dotenv@v2

      - name: Authenticate using service account
        run: 'echo "$GCP_SERVICE_ACCOUNT_KEY" > ./dbt/dbt-service-account.json'
        shell: bash
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}

      - name: Install dbt
        working-directory: ./dbt
        run: |
          pip install dbt-bigquery==1.4.1
          pip install elementary-data[bigquery]==0.7.5

      - name: Install dbt packages
        working-directory: ./dbt
        run: |
          dbt deps --target prod
      
      - name: Run dbt models
        working-directory: ./dbt
        run: |
          dbt run --target ${{ inputs.target }} --profiles-dir .
        env:
          GOOGLE_APPLICATION_CREDENTIALS:  ./dbt-service-account.json

      - name: Create and send Elementary report
        working-directory: ./dbt
        run: |
          edr send-report --google-service-account-path dbt-service-account.json --gcs-bucket-name t2d-elementary --update-bucket-website true

      - name: Test dbt models
        working-directory: .
        run: |
          dbt test --target ${{ inputs.target }} --profiles-dir .
        env:
          GOOGLE_APPLICATION_CREDENTIALS:  ./dbt-service-account.json
